name = "Santa is Coming Reloaded"
uid = "Santa-is-comi-ng03-90f1-0264a2479872"
version = 3
copyright = "CookieNoob and Ozonex"
description = "Santa is coming reloaded (with cookies). The mod transforms some of the rocks and trees into christmas gifts. The size of the gifts depends on the amount of reclaim in it. Maps with fewer trees/rocks will convert a higher fraction to gifts. Thanks to Black_Master for the GC model."
author = "CookieNoob (script) and Ozonex (models)"
icon = "/mods/Santa_Is_Coming_Reloaded/santa_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
